/*?php
$n1 =$_POST['numero1'];
$n2 =$_POST['numero2'];
$adicao = $_POST['adicao'];
$subtracao = $_POST['subtracao'];
$multiplicacao = $_POST['multiplicacao'];
$divisao = $_POST['divisao'];

if(isset($adicao)){
echo "Resultado da adição: ".($n1 + $n2);
}else if(isset($subtracao)){
echo "Resultado da subtração: ".($n1 - $n2);
}else if(isset($multiplicacao)){
echo "Resultado da multiplicação: ".($n1 * $n2);
}else if(isset($divisao)){
    echo "Resultado da divisão: ".($n1 / $n2);
}


?>*/ 